[package]
name = "footile"
version = "0.0.10"
authors = ["Douglas Lau <doug.p.lau@gmail.com>"]
description = "A 2D vector graphics library"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/footile"
homepage = "https://github.com/DougLau/footile"
repository = "https://github.com/DougLau/footile"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
png = "0.10"
palette = "0.2"
